import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
//   display: "swap",
// });

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "600"],  display: "swap" });

export const metadata: Metadata = {
  title: "Real Estate App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body

      className={poppins.className}
      >
        {children}
      </body>
    </html>
  );
}
